#!/bin/bash
# Mounts current directory to container an runs Maven commands
alias mvn='docker run -it --rm -v ~/.m2:/home/maven/.m2 -v `pwd`:/home/maven/repo -e MAVEN_CONFIG=/home/maven/.m2  docker.ftc-llc.net/build-maven:3.8.1 mvn'