apiVersion: v1
kind: Pod
spec:
  serviceAccountName: cicd-deployer
  imagePullSecrets:
  - name: regcred
  containers:
    - name: jnlp
      env:
        - name: SLACK_HOOK
          valueFrom:
            secretKeyRef:
              name: slack-hook
              key: slack-hook
    - name: maven
      image: maven:3.8.1-jdk-11
      env:
        - name: SONAR_HOST_URL
          value: "https://sonarqube.ftc-llc.net"
        - name: SONAR_LOGIN
          valueFrom:
            secretKeyRef:
              name: sonarqube-token
              key: token
      command:
      - sleep
      args:
      - infinity
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker
    - name: curl-jq
      image: badouralix/curl-jq:alpine
      env:
        - name: SONAR_LOGIN
          valueFrom:
            secretKeyRef:
              name: sonarqube-token
              key: token
        - name: SLACK_HOOK
          valueFrom:
            secretKeyRef:
              name: slack-hook
              key: slack-hook
      command:
        - sleep
      args:
        - 99d
    - name: gitversion
      image: docker.ftc-llc.net/gitversion:5.6.11
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /gitversion
          name: gitversion
      command:
        - sleep
      args:
        - infinity
    - name: gitops
      image: docker.ftc-llc.net/gitops:1.0.0
      command:
        - sleep
        - infinity
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /gitversion
          name: gitversion
        - mountPath: /env-test
          name: env-test
        - mountPath: /env-prod
          name: env-prod
        - mountPath: /root/.gitconfig
          name: github
          subPath: .gitconfig
        - mountPath: /root/.git-credentials
          name: github
          subPath: .git-credentials
    - name: auto-test
      image: docker.ftc-llc.net/dmos/dmos-test:current
      imagePullPolicy: Always
      env:
        - name: DMOS_TEST_DATASETS
          value: /app/datasets/local/
        - name: DMOS_TEST_SUITE
          value: DemoTestSuite.xml
      volumeMounts:
        - mountPath: /datasets
          name: test-datasets
      command:
        - sleep
      args:
        - infinity
  volumes:
    - name: jenkins-docker-cfg
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: gitversion
      emptyDir: {}
    - name: env-test
      emptyDir: {}
    - name: env-prod
      emptyDir: {}      
    - name: test-datasets
      emptyDir: {} 
    - name: github
      secret:
        secretName: github
